//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public int IdAgent { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string NameSurname { get; set; }
        public string Adress { get; set; }
        public string Adress2 { get; set; }
        public Nullable<int> Idzipcode { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public string MB { get; set; }
        public string OIB { get; set; }
        public string Telefon { get; set; }
        public string Telefax { get; set; }
        public string GSM { get; set; }
        public string email { get; set; }
        public string Web { get; set; }
        public string passwordAccount { get; set; }
        public string RoleAccount { get; set; }
        public string Type { get; set; }
        public string usertype { get; set; }
        public string username { get; set; }
        public byte[] password { get; set; }
        public string password2 { get; set; }
        public string remember_token { get; set; }
        public string role { get; set; }
        public string passwordFrontOffice { get; set; }
        public string RoleFrontOffice { get; set; }
        public string databases { get; set; }
        public string Firm { get; set; }
    }
}
