//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingResponse
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> BRType { get; set; }
        public Nullable<bool> Requ { get; set; }
    }
}
