//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelBookingRequirementRequest
    {
        public int Id { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public int BookingRequirementId { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
    }
}
