//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmBookingRequest
    {
        public int Id { get; set; }
        public string BookingComment { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public Nullable<int> BookingStatusID { get; set; }
        public Nullable<bool> Requ { get; set; }
        public Nullable<int> BookingID { get; set; }
    }
}
