//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETicket
    {
        public int Id { get; set; }
        public string ETicketNumber { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual SendEticketInfoRequest SendEticketInfoRequest { get; set; }
    }
}
