//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public string FlightId { get; set; }
        public string Airline { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string FlightCode { get; set; }
        public string FlightStatus { get; set; }
        public string FlightComment { get; set; }
        public string Class { get; set; }
        public string TicketLocator { get; set; }
        public string ETicketNumber { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<bool> Update_ { get; set; }
        public string PNR { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public Nullable<int> PassID_frontDesk { get; set; }
    }
}
