//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.ETicket = new HashSet<ETicket>();
            this.UpdateFlightsFlight = new HashSet<UpdateFlightsFlight>();
        }
    
        public int Id { get; set; }
        public string FlightId { get; set; }
        public string Airline { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string FlightCode { get; set; }
        public string FlightStatus { get; set; }
        public string FlightComment { get; set; }
        public string Class { get; set; }
        public string TicketLocator { get; set; }
        public string ETicketNumber { get; set; }
    
        public virtual ICollection<ETicket> ETicket { get; set; }
        public virtual ICollection<UpdateFlightsFlight> UpdateFlightsFlight { get; set; }
    }
}
