//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedmarModelContainer : DbContext
    {
        public MedmarModelContainer()
            : base("name=MedmarModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Service> ServiceSet { get; set; }
        public DbSet<Consumer> ConsumerSet { get; set; }
        public DbSet<requ_SendBookingRequirementRequest> requ_SendBookingRequirementRequestSet { get; set; }
        public DbSet<Person> PersonSet { get; set; }
        public DbSet<CancelBookingRequirementRequest> CancelBookingRequirementRequestSet { get; set; }
        public DbSet<ConfirmBookingRequest> ConfirmBookingRequestSet { get; set; }
        public DbSet<AcceptBookingRequest> AcceptBookingRequestSet { get; set; }
        public DbSet<CancelBookingRequest> CancelBookingRequestSet { get; set; }
        public DbSet<RequireTicketsRequest> RequireTicketsRequestSet { get; set; }
        public DbSet<BookingResponse> BookingResponseSet { get; set; }
        public DbSet<resp_SendAvailableBookingRequest> resp_SendAvailableBookingRequestSet { get; set; }
        public DbSet<Flight> FlightSet { get; set; }
        public DbSet<SendEticketInfoRequest> SendEticketInfoRequestSet { get; set; }
        public DbSet<ETicket> ETicketSet { get; set; }
        public DbSet<UpdateFlightDataRequest> UpdateFlightDataRequestSet { get; set; }
        public DbSet<UpdateFlightsFlight> UpdateFlightsFlightSet { get; set; }
        public DbSet<RequireDecisionRequest> RequireDecisionRequestSet { get; set; }
        public DbSet<RequirementResponse> RequirementResponseSet { get; set; }
    }
}
