//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string PassportIssuingCountry { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nationality { get; set; }
        public string SeamansBookNumber { get; set; }
        public Nullable<System.DateTime> SeamansBookExpiryDate { get; set; }
        public string SeamansBookIssuingCountry { get; set; }
        public string USVisaNumber { get; set; }
        public Nullable<System.DateTime> USVisaExpiryDate { get; set; }
        public string PersonComment { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> BookingRequirementIdHC { get; set; }
        public Nullable<int> PersonIDFrontDesk { get; set; }
    }
}
