//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedures
    {
        public int ID { get; set; }
        public string ProcName { get; set; }
        public string ProcCode { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<bool> Proccessed { get; set; }
    }
}
