//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequireDecisionRequest
    {
        public int Id { get; set; }
        public string BookingComment { get; set; }
        public Nullable<int> BookingStatusID { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public int BookingID { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
