//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementResponse
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsReceived { get; set; }
    
        public virtual resp_SendAvailableBookingRequest resp_SendAvailableBookingRequest { get; set; }
    }
}
