//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class requ_SendBookingRequirementRequest_history
    {
        public int Id { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> BookingRequirementIdHC { get; set; }
        public string RequestBookingComment { get; set; }
        public int Service_Id { get; set; }
        public int Person_Id { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequID { get; set; }
    }
}
