//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class resp_SendAvailableBookingRequest
    {
        public resp_SendAvailableBookingRequest()
        {
            this.AcceptBookingRequest = new HashSet<AcceptBookingRequest>();
            this.CancelBookingRequest = new HashSet<CancelBookingRequest>();
            this.ConfirmBookingRequest = new HashSet<ConfirmBookingRequest>();
            this.RequireDecisionRequest = new HashSet<RequireDecisionRequest>();
            this.SendEticketInfoRequest = new HashSet<SendEticketInfoRequest>();
            this.UpdateFlightDataRequest = new HashSet<UpdateFlightDataRequest>();
            this.RequirementResponse = new HashSet<RequirementResponse>();
        }
    
        public int Id { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> BookingStatusID { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public string BookingComment { get; set; }
        public Nullable<int> SpendTime { get; set; }
    
        public virtual ICollection<AcceptBookingRequest> AcceptBookingRequest { get; set; }
        public virtual ICollection<CancelBookingRequest> CancelBookingRequest { get; set; }
        public virtual ICollection<ConfirmBookingRequest> ConfirmBookingRequest { get; set; }
        public virtual requ_SendBookingRequirementRequest requ_SendBookingRequirementRequest { get; set; }
        public virtual ICollection<RequireDecisionRequest> RequireDecisionRequest { get; set; }
        public virtual ICollection<SendEticketInfoRequest> SendEticketInfoRequest { get; set; }
        public virtual ICollection<UpdateFlightDataRequest> UpdateFlightDataRequest { get; set; }
        public virtual ICollection<RequirementResponse> RequirementResponse { get; set; }
    }
}
