//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class resp_SendAvailableBookingRequest
    {
        public int Id { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> BookingStatusID { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public string BookingComment { get; set; }
        public Nullable<int> SpendTime { get; set; }
        public int requ_SendBookingRequirementRequest_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public Nullable<int> TAstatus { get; set; }
        public Nullable<bool> FlagUndefFlightStatus { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<int> RequDescisionCounter { get; set; }
    }
}
