//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendEticketInfoRequest
    {
        public SendEticketInfoRequest()
        {
            this.ETicket = new HashSet<ETicket>();
        }
    
        public int Id { get; set; }
        public string BookingComment { get; set; }
        public Nullable<int> BookingStatusID { get; set; }
    
        public virtual ICollection<ETicket> ETicket { get; set; }
        public virtual resp_SendAvailableBookingRequest resp_SendAvailableBookingRequest { get; set; }
    }
}
