//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatus
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> UpdateInitial { get; set; }
        public Nullable<bool> Requ { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SendReady { get; set; }
        public Nullable<bool> Sent { get; set; }
    }
}
