//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedmarDBDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.requ_SendBookingRequirementRequest = new HashSet<requ_SendBookingRequirementRequest>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Requ { get; set; }
        public Nullable<int> SessionID { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual ICollection<requ_SendBookingRequirementRequest> requ_SendBookingRequirementRequest { get; set; }
    }
}
