//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PullWS.serviceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://myservices.com/besoft/medmarTest", ConfigurationName="serviceTest.indexSoap")]
    public interface indexSoap {
        
        // CODEGEN: Generating message contract since element name GandalfResult from namespace http://myservices.com/besoft/medmarTest is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.com/besoft/medmarTest/Gandalf", ReplyAction="*")]
        PullWS.serviceTest.GandalfResponse Gandalf(PullWS.serviceTest.GandalfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://myservices.com/besoft/medmarTest/Gandalf", ReplyAction="*")]
        System.Threading.Tasks.Task<PullWS.serviceTest.GandalfResponse> GandalfAsync(PullWS.serviceTest.GandalfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GandalfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Gandalf", Namespace="http://myservices.com/besoft/medmarTest", Order=0)]
        public PullWS.serviceTest.GandalfRequestBody Body;
        
        public GandalfRequest() {
        }
        
        public GandalfRequest(PullWS.serviceTest.GandalfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GandalfRequestBody {
        
        public GandalfRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GandalfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GandalfResponse", Namespace="http://myservices.com/besoft/medmarTest", Order=0)]
        public PullWS.serviceTest.GandalfResponseBody Body;
        
        public GandalfResponse() {
        }
        
        public GandalfResponse(PullWS.serviceTest.GandalfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://myservices.com/besoft/medmarTest")]
    public partial class GandalfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GandalfResult;
        
        public GandalfResponseBody() {
        }
        
        public GandalfResponseBody(string GandalfResult) {
            this.GandalfResult = GandalfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface indexSoapChannel : PullWS.serviceTest.indexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class indexSoapClient : System.ServiceModel.ClientBase<PullWS.serviceTest.indexSoap>, PullWS.serviceTest.indexSoap {
        
        public indexSoapClient() {
        }
        
        public indexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public indexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public indexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public indexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullWS.serviceTest.GandalfResponse PullWS.serviceTest.indexSoap.Gandalf(PullWS.serviceTest.GandalfRequest request) {
            return base.Channel.Gandalf(request);
        }
        
        public string Gandalf() {
            PullWS.serviceTest.GandalfRequest inValue = new PullWS.serviceTest.GandalfRequest();
            inValue.Body = new PullWS.serviceTest.GandalfRequestBody();
            PullWS.serviceTest.GandalfResponse retVal = ((PullWS.serviceTest.indexSoap)(this)).Gandalf(inValue);
            return retVal.Body.GandalfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullWS.serviceTest.GandalfResponse> PullWS.serviceTest.indexSoap.GandalfAsync(PullWS.serviceTest.GandalfRequest request) {
            return base.Channel.GandalfAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullWS.serviceTest.GandalfResponse> GandalfAsync() {
            PullWS.serviceTest.GandalfRequest inValue = new PullWS.serviceTest.GandalfRequest();
            inValue.Body = new PullWS.serviceTest.GandalfRequestBody();
            return ((PullWS.serviceTest.indexSoap)(this)).GandalfAsync(inValue);
        }
    }
}
