//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PullWS.synchronize {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceConsumerRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class WebServiceConsumerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.AcceptBookingRequest[] AcceptBookingRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.CancelBookingRequest[] CancelBookingRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.CancelBookingRequirementRequest[] CancelBookingRequirementRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] CancelBookingResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] ConfirmBookingResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] RequestIssuingDecisionResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.RequireTicketsRequest[] RequireTicketsRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] SendAvailableBookingResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.SendBookingRequirementRequest[] SendBookingRequirementRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] SendEticketInfoResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] UpdateFlightDataResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.AcceptBookingRequest[] AcceptBookingRequests {
            get {
                return this.AcceptBookingRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptBookingRequestsField, value) != true)) {
                    this.AcceptBookingRequestsField = value;
                    this.RaisePropertyChanged("AcceptBookingRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.CancelBookingRequest[] CancelBookingRequests {
            get {
                return this.CancelBookingRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingRequestsField, value) != true)) {
                    this.CancelBookingRequestsField = value;
                    this.RaisePropertyChanged("CancelBookingRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.CancelBookingRequirementRequest[] CancelBookingRequirementRequests {
            get {
                return this.CancelBookingRequirementRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingRequirementRequestsField, value) != true)) {
                    this.CancelBookingRequirementRequestsField = value;
                    this.RaisePropertyChanged("CancelBookingRequirementRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] CancelBookingResponses {
            get {
                return this.CancelBookingResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingResponsesField, value) != true)) {
                    this.CancelBookingResponsesField = value;
                    this.RaisePropertyChanged("CancelBookingResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] ConfirmBookingResponses {
            get {
                return this.ConfirmBookingResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmBookingResponsesField, value) != true)) {
                    this.ConfirmBookingResponsesField = value;
                    this.RaisePropertyChanged("ConfirmBookingResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] RequestIssuingDecisionResponses {
            get {
                return this.RequestIssuingDecisionResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIssuingDecisionResponsesField, value) != true)) {
                    this.RequestIssuingDecisionResponsesField = value;
                    this.RaisePropertyChanged("RequestIssuingDecisionResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.RequireTicketsRequest[] RequireTicketsRequests {
            get {
                return this.RequireTicketsRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequireTicketsRequestsField, value) != true)) {
                    this.RequireTicketsRequestsField = value;
                    this.RaisePropertyChanged("RequireTicketsRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] SendAvailableBookingResponses {
            get {
                return this.SendAvailableBookingResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.SendAvailableBookingResponsesField, value) != true)) {
                    this.SendAvailableBookingResponsesField = value;
                    this.RaisePropertyChanged("SendAvailableBookingResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.SendBookingRequirementRequest[] SendBookingRequirementRequests {
            get {
                return this.SendBookingRequirementRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.SendBookingRequirementRequestsField, value) != true)) {
                    this.SendBookingRequirementRequestsField = value;
                    this.RaisePropertyChanged("SendBookingRequirementRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] SendEticketInfoResponses {
            get {
                return this.SendEticketInfoResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.SendEticketInfoResponsesField, value) != true)) {
                    this.SendEticketInfoResponsesField = value;
                    this.RaisePropertyChanged("SendEticketInfoResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] UpdateFlightDataResponses {
            get {
                return this.UpdateFlightDataResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateFlightDataResponsesField, value) != true)) {
                    this.UpdateFlightDataResponsesField = value;
                    this.RaisePropertyChanged("UpdateFlightDataResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcceptBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class AcceptBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class CancelBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelBookingRequirementRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class CancelBookingRequirementRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingRequirementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingRequirementId {
            get {
                return this.BookingRequirementIdField;
            }
            set {
                if ((this.BookingRequirementIdField.Equals(value) != true)) {
                    this.BookingRequirementIdField = value;
                    this.RaisePropertyChanged("BookingRequirementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingResponse", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class BookingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReceived {
            get {
                return this.IsReceivedField;
            }
            set {
                if ((this.IsReceivedField.Equals(value) != true)) {
                    this.IsReceivedField = value;
                    this.RaisePropertyChanged("IsReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequireTicketsRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class RequireTicketsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendBookingRequirementRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class SendBookingRequirementRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingRequirementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestBookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAirportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingRequirementId {
            get {
                return this.BookingRequirementIdField;
            }
            set {
                if ((this.BookingRequirementIdField.Equals(value) != true)) {
                    this.BookingRequirementIdField = value;
                    this.RaisePropertyChanged("BookingRequirementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAirport {
            get {
                return this.FromAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAirportField, value) != true)) {
                    this.FromAirportField = value;
                    this.RaisePropertyChanged("FromAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestBookingComment {
            get {
                return this.RequestBookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestBookingCommentField, value) != true)) {
                    this.RequestBookingCommentField = value;
                    this.RaisePropertyChanged("RequestBookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAirport {
            get {
                return this.ToAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAirportField, value) != true)) {
                    this.ToAirportField = value;
                    this.RaisePropertyChanged("ToAirport");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PassportExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportIssuingCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SeamansBookExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeamansBookIssuingCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeamansBookNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime USVisaExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USVisaNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PassportExpiryDate {
            get {
                return this.PassportExpiryDateField;
            }
            set {
                if ((this.PassportExpiryDateField.Equals(value) != true)) {
                    this.PassportExpiryDateField = value;
                    this.RaisePropertyChanged("PassportExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportIssuingCountry {
            get {
                return this.PassportIssuingCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportIssuingCountryField, value) != true)) {
                    this.PassportIssuingCountryField = value;
                    this.RaisePropertyChanged("PassportIssuingCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNumber {
            get {
                return this.PassportNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumberField, value) != true)) {
                    this.PassportNumberField = value;
                    this.RaisePropertyChanged("PassportNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonComment {
            get {
                return this.PersonCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonCommentField, value) != true)) {
                    this.PersonCommentField = value;
                    this.RaisePropertyChanged("PersonComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfBirth {
            get {
                return this.PlaceOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceOfBirthField, value) != true)) {
                    this.PlaceOfBirthField = value;
                    this.RaisePropertyChanged("PlaceOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SeamansBookExpiryDate {
            get {
                return this.SeamansBookExpiryDateField;
            }
            set {
                if ((this.SeamansBookExpiryDateField.Equals(value) != true)) {
                    this.SeamansBookExpiryDateField = value;
                    this.RaisePropertyChanged("SeamansBookExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeamansBookIssuingCountry {
            get {
                return this.SeamansBookIssuingCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SeamansBookIssuingCountryField, value) != true)) {
                    this.SeamansBookIssuingCountryField = value;
                    this.RaisePropertyChanged("SeamansBookIssuingCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeamansBookNumber {
            get {
                return this.SeamansBookNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SeamansBookNumberField, value) != true)) {
                    this.SeamansBookNumberField = value;
                    this.RaisePropertyChanged("SeamansBookNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime USVisaExpiryDate {
            get {
                return this.USVisaExpiryDateField;
            }
            set {
                if ((this.USVisaExpiryDateField.Equals(value) != true)) {
                    this.USVisaExpiryDateField = value;
                    this.RaisePropertyChanged("USVisaExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USVisaNumber {
            get {
                return this.USVisaNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.USVisaNumberField, value) != true)) {
                    this.USVisaNumberField = value;
                    this.RaisePropertyChanged("USVisaNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceProviderResponse", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class WebServiceProviderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] AcceptBookingResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.CancelBookingRequest[] CancelBookingRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.RequirementResponse[] CancelBookingRequirementResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] CancelBookingResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.ConfirmBookingRequest[] ConfirmBookingRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.RequireDecisionRequest[] RequireDecisionRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.BookingResponse[] RequireTicketsResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.SendAvailableBookingRequest[] SendAvailableBookingRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.RequirementResponse[] SendBookingRequirementResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.SendEticketInfoRequest[] SendEticketInfoRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.UpdateFlightDataRequest[] UpdateFlightDataRequestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] AcceptBookingResponses {
            get {
                return this.AcceptBookingResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.AcceptBookingResponsesField, value) != true)) {
                    this.AcceptBookingResponsesField = value;
                    this.RaisePropertyChanged("AcceptBookingResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.CancelBookingRequest[] CancelBookingRequests {
            get {
                return this.CancelBookingRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingRequestsField, value) != true)) {
                    this.CancelBookingRequestsField = value;
                    this.RaisePropertyChanged("CancelBookingRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.RequirementResponse[] CancelBookingRequirementResponses {
            get {
                return this.CancelBookingRequirementResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingRequirementResponsesField, value) != true)) {
                    this.CancelBookingRequirementResponsesField = value;
                    this.RaisePropertyChanged("CancelBookingRequirementResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] CancelBookingResponses {
            get {
                return this.CancelBookingResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.CancelBookingResponsesField, value) != true)) {
                    this.CancelBookingResponsesField = value;
                    this.RaisePropertyChanged("CancelBookingResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.ConfirmBookingRequest[] ConfirmBookingRequests {
            get {
                return this.ConfirmBookingRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmBookingRequestsField, value) != true)) {
                    this.ConfirmBookingRequestsField = value;
                    this.RaisePropertyChanged("ConfirmBookingRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.RequireDecisionRequest[] RequireDecisionRequests {
            get {
                return this.RequireDecisionRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequireDecisionRequestsField, value) != true)) {
                    this.RequireDecisionRequestsField = value;
                    this.RaisePropertyChanged("RequireDecisionRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.BookingResponse[] RequireTicketsResponses {
            get {
                return this.RequireTicketsResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.RequireTicketsResponsesField, value) != true)) {
                    this.RequireTicketsResponsesField = value;
                    this.RaisePropertyChanged("RequireTicketsResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.SendAvailableBookingRequest[] SendAvailableBookingRequests {
            get {
                return this.SendAvailableBookingRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.SendAvailableBookingRequestsField, value) != true)) {
                    this.SendAvailableBookingRequestsField = value;
                    this.RaisePropertyChanged("SendAvailableBookingRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.RequirementResponse[] SendBookingRequirementResponses {
            get {
                return this.SendBookingRequirementResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.SendBookingRequirementResponsesField, value) != true)) {
                    this.SendBookingRequirementResponsesField = value;
                    this.RaisePropertyChanged("SendBookingRequirementResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.SendEticketInfoRequest[] SendEticketInfoRequests {
            get {
                return this.SendEticketInfoRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.SendEticketInfoRequestsField, value) != true)) {
                    this.SendEticketInfoRequestsField = value;
                    this.RaisePropertyChanged("SendEticketInfoRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.UpdateFlightDataRequest[] UpdateFlightDataRequests {
            get {
                return this.UpdateFlightDataRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateFlightDataRequestsField, value) != true)) {
                    this.UpdateFlightDataRequestsField = value;
                    this.RaisePropertyChanged("UpdateFlightDataRequests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequirementResponse", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class RequirementResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingRequirementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingRequirementId {
            get {
                return this.BookingRequirementIdField;
            }
            set {
                if ((this.BookingRequirementIdField.Equals(value) != true)) {
                    this.BookingRequirementIdField = value;
                    this.RaisePropertyChanged("BookingRequirementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReceived {
            get {
                return this.IsReceivedField;
            }
            set {
                if ((this.IsReceivedField.Equals(value) != true)) {
                    this.IsReceivedField = value;
                    this.RaisePropertyChanged("IsReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class ConfirmBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingComment {
            get {
                return this.BookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCommentField, value) != true)) {
                    this.BookingCommentField = value;
                    this.RaisePropertyChanged("BookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeLimit {
            get {
                return this.TimeLimitField;
            }
            set {
                if ((this.TimeLimitField.Equals(value) != true)) {
                    this.TimeLimitField = value;
                    this.RaisePropertyChanged("TimeLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequireDecisionRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class RequireDecisionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingComment {
            get {
                return this.BookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCommentField, value) != true)) {
                    this.BookingCommentField = value;
                    this.RaisePropertyChanged("BookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeLimit {
            get {
                return this.TimeLimitField;
            }
            set {
                if ((this.TimeLimitField.Equals(value) != true)) {
                    this.TimeLimitField = value;
                    this.RaisePropertyChanged("TimeLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendAvailableBookingRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class SendAvailableBookingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingRequirementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.Flight[] FlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAirportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingComment {
            get {
                return this.BookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCommentField, value) != true)) {
                    this.BookingCommentField = value;
                    this.RaisePropertyChanged("BookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingRequirementId {
            get {
                return this.BookingRequirementIdField;
            }
            set {
                if ((this.BookingRequirementIdField.Equals(value) != true)) {
                    this.BookingRequirementIdField = value;
                    this.RaisePropertyChanged("BookingRequirementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.Flight[] Flights {
            get {
                return this.FlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightsField, value) != true)) {
                    this.FlightsField = value;
                    this.RaisePropertyChanged("Flights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAirport {
            get {
                return this.FromAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAirportField, value) != true)) {
                    this.FromAirportField = value;
                    this.RaisePropertyChanged("FromAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpendTime {
            get {
                return this.SpendTimeField;
            }
            set {
                if ((this.SpendTimeField.Equals(value) != true)) {
                    this.SpendTimeField = value;
                    this.RaisePropertyChanged("SpendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeLimit {
            get {
                return this.TimeLimitField;
            }
            set {
                if ((this.TimeLimitField.Equals(value) != true)) {
                    this.TimeLimitField = value;
                    this.RaisePropertyChanged("TimeLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAirport {
            get {
                return this.ToAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAirportField, value) != true)) {
                    this.ToAirportField = value;
                    this.RaisePropertyChanged("ToAirport");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEticketInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class SendEticketInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.ETicket[] ETicketsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingComment {
            get {
                return this.BookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCommentField, value) != true)) {
                    this.BookingCommentField = value;
                    this.RaisePropertyChanged("BookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.ETicket[] ETickets {
            get {
                return this.ETicketsField;
            }
            set {
                if ((object.ReferenceEquals(this.ETicketsField, value) != true)) {
                    this.ETicketsField = value;
                    this.RaisePropertyChanged("ETickets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFlightDataRequest", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class UpdateFlightDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PullWS.synchronize.Flight[] FlightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpendTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingComment {
            get {
                return this.BookingCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCommentField, value) != true)) {
                    this.BookingCommentField = value;
                    this.RaisePropertyChanged("BookingComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookingStatus {
            get {
                return this.BookingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingStatusField, value) != true)) {
                    this.BookingStatusField = value;
                    this.RaisePropertyChanged("BookingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PullWS.synchronize.Flight[] Flights {
            get {
                return this.FlightsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightsField, value) != true)) {
                    this.FlightsField = value;
                    this.RaisePropertyChanged("Flights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpendTime {
            get {
                return this.SpendTimeField;
            }
            set {
                if ((this.SpendTimeField.Equals(value) != true)) {
                    this.SpendTimeField = value;
                    this.RaisePropertyChanged("SpendTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeLimit {
            get {
                return this.TimeLimitField;
            }
            set {
                if ((this.TimeLimitField.Equals(value) != true)) {
                    this.TimeLimitField = value;
                    this.RaisePropertyChanged("TimeLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETicketNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAirportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketLocatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAirportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Airline {
            get {
                return this.AirlineField;
            }
            set {
                if ((object.ReferenceEquals(this.AirlineField, value) != true)) {
                    this.AirlineField = value;
                    this.RaisePropertyChanged("Airline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETicketNumber {
            get {
                return this.ETicketNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ETicketNumberField, value) != true)) {
                    this.ETicketNumberField = value;
                    this.RaisePropertyChanged("ETicketNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightCode {
            get {
                return this.FlightCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightCodeField, value) != true)) {
                    this.FlightCodeField = value;
                    this.RaisePropertyChanged("FlightCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightComment {
            get {
                return this.FlightCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightCommentField, value) != true)) {
                    this.FlightCommentField = value;
                    this.RaisePropertyChanged("FlightComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightId {
            get {
                return this.FlightIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightIdField, value) != true)) {
                    this.FlightIdField = value;
                    this.RaisePropertyChanged("FlightId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightStatus {
            get {
                return this.FlightStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightStatusField, value) != true)) {
                    this.FlightStatusField = value;
                    this.RaisePropertyChanged("FlightStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAirport {
            get {
                return this.FromAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAirportField, value) != true)) {
                    this.FromAirportField = value;
                    this.RaisePropertyChanged("FromAirport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketLocator {
            get {
                return this.TicketLocatorField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketLocatorField, value) != true)) {
                    this.TicketLocatorField = value;
                    this.RaisePropertyChanged("TicketLocator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAirport {
            get {
                return this.ToAirportField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAirportField, value) != true)) {
                    this.ToAirportField = value;
                    this.RaisePropertyChanged("ToAirport");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETicket", Namespace="http://schemas.datacontract.org/2004/07/TravelService")]
    [System.SerializableAttribute()]
    public partial class ETicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETicketNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETicketNumber {
            get {
                return this.ETicketNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ETicketNumberField, value) != true)) {
                    this.ETicketNumberField = value;
                    this.RaisePropertyChanged("ETicketNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightId {
            get {
                return this.FlightIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightIdField, value) != true)) {
                    this.FlightIdField = value;
                    this.RaisePropertyChanged("FlightId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.medmar.eu/TravelService_.svc", ConfigurationName="synchronize.ITravelService")]
    public interface ITravelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.medmar.eu/TravelService_.svc/ITravelService/synchronize", ReplyAction="http://www.medmar.eu/TravelService_.svc/ITravelService/synchronizeResponse")]
        PullWS.synchronize.WebServiceProviderResponse synchronize(PullWS.synchronize.WebServiceConsumerRequest webServiceConsumerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.medmar.eu/TravelService_.svc/ITravelService/synchronize", ReplyAction="http://www.medmar.eu/TravelService_.svc/ITravelService/synchronizeResponse")]
        System.Threading.Tasks.Task<PullWS.synchronize.WebServiceProviderResponse> synchronizeAsync(PullWS.synchronize.WebServiceConsumerRequest webServiceConsumerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.medmar.eu/TravelService_.svc/ITravelService/test", ReplyAction="http://www.medmar.eu/TravelService_.svc/ITravelService/testResponse")]
        string test(int nmb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.medmar.eu/TravelService_.svc/ITravelService/test", ReplyAction="http://www.medmar.eu/TravelService_.svc/ITravelService/testResponse")]
        System.Threading.Tasks.Task<string> testAsync(int nmb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelServiceChannel : PullWS.synchronize.ITravelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelServiceClient : System.ServiceModel.ClientBase<PullWS.synchronize.ITravelService>, PullWS.synchronize.ITravelService {
        
        public TravelServiceClient() {
        }
        
        public TravelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TravelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PullWS.synchronize.WebServiceProviderResponse synchronize(PullWS.synchronize.WebServiceConsumerRequest webServiceConsumerRequest) {
            return base.Channel.synchronize(webServiceConsumerRequest);
        }
        
        public System.Threading.Tasks.Task<PullWS.synchronize.WebServiceProviderResponse> synchronizeAsync(PullWS.synchronize.WebServiceConsumerRequest webServiceConsumerRequest) {
            return base.Channel.synchronizeAsync(webServiceConsumerRequest);
        }
        
        public string test(int nmb) {
            return base.Channel.test(nmb);
        }
        
        public System.Threading.Tasks.Task<string> testAsync(int nmb) {
            return base.Channel.testAsync(nmb);
        }
    }
}
